name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo 'Hello! GitHub Actions is working!'

      - name: Print the date
        run: date

      - name: List files
        run: ls -la

